"""добавÐдобавили ыегÐstudent_id

Revision ID: ab520e184e55
Revises: 5ec3bb694105
Create Date: 2024-04-18 17:30:30.512110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab520e184e55'
down_revision: Union[str, None] = '5ec3bb694105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('themes', sa.Column('student_id', sa.Integer(), nullable=True))
    op.drop_column('themes', 'is_accepted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('is_accepted', sa.BOOLEAN(), nullable=True))
    op.drop_column('themes', 'student_id')
    op.drop_column('themes', 'status')
    # ### end Alembic commands ###
